// OpenFOAM built-in command database
//
// Case files are generated by src/lib/case-templates.ts; the hand-written case
// and file templates that used to live here were imported by nothing and were
// removed on 2026-09-10.
//
// Commands carry an optional `minVersion` (major OpenFOAM version that introduced
// them). The Command Panel filters the list against the active OpenFOAM version
// (returned by /api/wsl?action=version) so users only see commands that actually
// exist in their installed version. Commands without `minVersion` are valid for
// every supported version (OpenFOAM 9+).

export interface OpenFOAMCommand {
  name: string;
  category: string;
  description: string;
  syntax: string;
  commonOptions?: string;
  /** Minimum OpenFOAM major version that ships this command. */
  minVersion?: number;
}

export const COMMAND_CATEGORIES = [
  'Execution',
  'Mesh Generation',
  'Mesh Utilities',
  'Pre-processing',
  'Post-processing',
  'Parallel Processing',
  'Field Utilities',
  'Sampling & Probes',
  'Surface Utilities',
  'Case Management',
  'Solver Modules',
  'Mesh Conversion',
  'Compilation & Debug',
  'Units & Dimensions',
] as const;

export const OPENFOAM_COMMANDS: OpenFOAMCommand[] = [
  // ═══════════════════════════════════════════════════════
  // EXECUTION — foamRun / foamMultiRun (introduced in v11, mainstream since v13)
  // ═══════════════════════════════════════════════════════
  { name: 'foamRun', category: 'Execution', minVersion: 11, description: 'Runs the solver module specified in system/controlDict (replaces simpleFoam, pimpleFoam, etc.)', syntax: 'foamRun', commonOptions: '-case <dir>, -parallel, -solver <name>' },
  { name: 'foamRun > log', category: 'Execution', minVersion: 11, description: 'Runs the solver and saves output to a log file (stdout+stderr)', syntax: 'foamRun > log.foamRun 2>&1 &', commonOptions: '' },
  { name: 'foamMultiRun', category: 'Execution', minVersion: 11, description: 'Runs a solver module for each region of a multi-region simulation (e.g. CHT)', syntax: 'foamMultiRun', commonOptions: '-case <dir>, -parallel' },
  { name: 'foamInitializeFields', category: 'Execution', minVersion: 14, description: 'Initializes fields using the new field functions and functionalFixedValue BC (v14)', syntax: 'foamInitializeFields', commonOptions: '-case <dir>' },

  // ═══════════════════════════════════════════════════════
  // MESH GENERATION
  // ═══════════════════════════════════════════════════════
  { name: 'blockMesh', category: 'Mesh Generation', description: 'Generates the block mesh from the blockMeshDict file in system/', syntax: 'blockMesh', commonOptions: '-case <dir>' },
  { name: 'snappyHexMesh', category: 'Mesh Generation', description: 'Generates a mesh conforming to STL geometries with adaptive refinement', syntax: 'snappyHexMesh', commonOptions: '-parallel, -dict <file>, -checkGeometry, -noOverwrite' },
  { name: 'cartesianMesh', category: 'Mesh Generation', description: 'Cartesian meshing (cfMesh)', syntax: 'cartesianMesh', commonOptions: '' },
  { name: 'pMesh', category: 'Mesh Generation', description: 'Polyhedral meshing (cfMesh)', syntax: 'pMesh', commonOptions: '' },
  { name: 'tetMesh', category: 'Mesh Generation', description: 'Tetrahedral meshing (cfMesh)', syntax: 'tetMesh', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // MESH CONVERSION (from other formats)
  // ═══════════════════════════════════════════════════════
  { name: 'gmshToFoam', category: 'Mesh Conversion', description: 'Converts Gmsh (.msh) mesh into OpenFOAM format', syntax: 'gmshToFoam <file.msh>', commonOptions: '' },
  { name: 'fluent3DMeshToFoam', category: 'Mesh Conversion', description: 'Converts Fluent 3D (.msh) mesh into OpenFOAM format', syntax: 'fluent3DMeshToFoam <file.msh>', commonOptions: '' },
  { name: 'ansysToFoam', category: 'Mesh Conversion', description: 'Converts ANSYS mesh into OpenFOAM format', syntax: 'ansysToFoam <file>', commonOptions: '' },
  { name: 'star4ToFoam', category: 'Mesh Conversion', description: 'Converts STAR-CD mesh into OpenFOAM format', syntax: 'star4ToFoam <file>', commonOptions: '' },
  { name: 'ideasToFoam', category: 'Mesh Conversion', description: 'Converts I-DEAS (.unv) mesh into OpenFOAM format', syntax: 'ideasToFoam <file.unv>', commonOptions: '' },
  { name: 'kivaToFoam', category: 'Mesh Conversion', description: 'Converts KIVA3V mesh into OpenFOAM format', syntax: 'kivaToFoam <file>', commonOptions: '' },
  { name: 'mshToFoam', category: 'Mesh Conversion', description: 'Converts generic msh-format mesh', syntax: 'mshToFoam <file.msh>', commonOptions: '' },
  { name: 'netgenNeutralToFoam', category: 'Mesh Conversion', description: 'Converts NETGEN mesh into OpenFOAM format', syntax: 'netgenNeutralToFoam <file>', commonOptions: '' },
  { name: 'plot3dToFoam', category: 'Mesh Conversion', description: 'Converts PLOT3D mesh into OpenFOAM format', syntax: 'plot3dToFoam <file>', commonOptions: '' },
  { name: 'tetgenToFoam', category: 'Mesh Conversion', description: 'Converts Tetgen mesh into OpenFOAM format', syntax: 'tetgenToFoam <file>', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // MESH UTILITIES
  // ═══════════════════════════════════════════════════════
  { name: 'checkMesh', category: 'Mesh Utilities', description: 'Checks mesh quality (aspect ratio, non-orthogonality, skewness)', syntax: 'checkMesh', commonOptions: '-case <dir>, -allTopology, -noZero' },
  { name: 'refineMesh', category: 'Mesh Utilities', description: 'Refines the mesh globally or in specific regions', syntax: 'refineMesh', commonOptions: '-all, -noOverwrite' },
  { name: 'mirrorMesh', category: 'Mesh Utilities', description: 'Creates a mirrored domain', syntax: 'mirrorMesh', commonOptions: '' },
  { name: 'mergeMeshes', category: 'Mesh Utilities', description: 'Merges two or more meshes', syntax: 'mergeMeshes <case1> <case2> <outputCase>', commonOptions: '' },
  { name: 'splitMeshRegions', category: 'Mesh Utilities', description: 'Splits the mesh into regions (for multi-region cases)', syntax: 'splitMeshRegions', commonOptions: '-cellZones, -noOverwrite' },
  { name: 'stitchMesh', category: 'Mesh Utilities', description: 'Stitches adjacent patches', syntax: 'stitchMesh <masterPatch> <slavePatch>', commonOptions: '-tolerance <val>' },
  { name: 'transformPoints', category: 'Mesh Utilities', description: 'Translates, rotates or scales the mesh', syntax: 'transformPoints "rotate=(...) (..., ...) ..."', commonOptions: '-scale <factor>' },
  { name: 'makeAxialMesh', category: 'Mesh Utilities', description: 'Converts a 3D mesh into an axisymmetric mesh', syntax: 'makeAxialMesh', commonOptions: '-axis <point> <point>' },
  { name: 'collapseEdges', category: 'Mesh Utilities', description: 'Collapses short mesh edges', syntax: 'collapseEdges', commonOptions: '-noOverwrite' },
  { name: 'modifyMesh', category: 'Mesh Utilities', description: 'Modifies the mesh (removes/hides cells)', syntax: 'modifyMesh', commonOptions: '-patch <name> -set <cellSet>' },
  { name: 'smoothMesh', category: 'Mesh Utilities', description: 'Smooths the mesh with a Laplacian', syntax: 'smoothMesh', commonOptions: '-noOverwrite' },
  { name: 'extrudeMesh', category: 'Mesh Utilities', description: 'Extrudes a 2D mesh into 3D', syntax: 'extrudeMesh', commonOptions: '' },
  { name: 'extrudeToRegionMesh', category: 'Mesh Utilities', description: 'Extrudes a patch into a new region', syntax: 'extrudeToRegionMesh', commonOptions: '' },
  { name: 'renumberMesh', category: 'Mesh Utilities', description: 'Renumbers cells to improve the sparse matrix', syntax: 'renumberMesh', commonOptions: '-noOverwrite' },
  { name: 'writeCellCentres', category: 'Mesh Utilities', description: 'Writes cell centres as fields', syntax: 'writeCellCentres', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // PRE-PROCESSING
  // ═══════════════════════════════════════════════════════
  { name: 'setFields', category: 'Pre-processing', description: 'Sets initial values for fields', syntax: 'setFields', commonOptions: '-case <dir>' },
  { name: 'setExprFields', category: 'Pre-processing', description: 'Sets fields with mathematical expressions', syntax: 'setExprFields', commonOptions: '' },
  { name: 'initTopoSet', category: 'Pre-processing', description: 'Initializes topological sets (cellSet, faceSet, pointSet)', syntax: 'initTopoSet', commonOptions: '' },
  { name: 'topoSet', category: 'Pre-processing', description: 'Creates and modifies topological sets', syntax: 'topoSet', commonOptions: '' },
  { name: 'createPatch', category: 'Pre-processing', description: 'Creates/modifies patches', syntax: 'createPatch', commonOptions: '-noOverwrite, -dict <file>' },
  { name: 'autoPatch', category: 'Pre-processing', description: 'Groups faces into patches automatically by angle', syntax: 'autoPatch <angle>', commonOptions: '-noOverwrite' },
  { name: 'surfaceFeatureExtract', category: 'Pre-processing', description: 'Extracts feature edges from STL for snappyHexMesh', syntax: 'surfaceFeatureExtract', commonOptions: '' },
  { name: 'surfaceCheck', category: 'Pre-processing', description: 'Checks STL surface', syntax: 'surfaceCheck <file.stl>', commonOptions: '' },
  { name: 'decomposePar', category: 'Pre-processing', description: 'Decomposes the case for parallel computation (decomposeParDict)', syntax: 'decomposePar', commonOptions: '-force' },

  // ═══════════════════════════════════════════════════════
  // POST-PROCESSING
  // ═══════════════════════════════════════════════════════
  { name: 'foamPostProcess', category: 'Post-processing', description: 'Runs post-processing functions (funObjects) defined in controlDict', syntax: 'foamPostProcess', commonOptions: '-func <name>, -latestTime, -time <t>' },
  { name: 'foamCalc', category: 'Post-processing', description: 'Computes derived fields (vorticity, divergence, gradient, mag, etc.)', syntax: 'foamCalc <component> <field>', commonOptions: '' },
  { name: 'foamListTimes', category: 'Post-processing', description: 'Lists the saved timesteps in the case', syntax: 'foamListTimes', commonOptions: '-rm, -latestTime, -time <t>' },
  { name: 'foamGetRange', category: 'Post-processing', description: 'Shows the range of available timesteps', syntax: 'foamGetRange', commonOptions: '' },
  { name: 'paraFoam', category: 'Post-processing', description: 'Launches ParaView for visualization (requires X11 display)', syntax: 'paraFoam -builtin', commonOptions: '-builtin, -case <dir>' },
  { name: 'patchAverage', category: 'Post-processing', description: 'Computes the average of a field over a patch', syntax: 'patchAverage <field> <patch>', commonOptions: '' },
  { name: 'patchIntegrate', category: 'Post-processing', description: 'Integrates a field over a patch', syntax: 'patchIntegrate <field> <patch>', commonOptions: '' },
  { name: 'wallShearStress', category: 'Post-processing', description: 'Computes the wall shear stress', syntax: 'wallShearStress', commonOptions: '' },
  { name: 'yPlusRAS', category: 'Post-processing', description: 'Computes y+ for RANS', syntax: 'yPlusRAS', commonOptions: '' },
  { name: 'yPlusLES', category: 'Post-processing', description: 'Computes y+ for LES', syntax: 'yPlusLES', commonOptions: '' },
  { name: 'turbulenceFields', category: 'Post-processing', description: 'Generates turbulence fields (k, epsilon, omega, nuTilda, R, L)', syntax: 'turbulenceFields', commonOptions: '' },
  { name: 'vorticity', category: 'Post-processing', description: 'Computes the vorticity field', syntax: 'vorticity', commonOptions: '' },
  { name: 'pressureDifference', category: 'Post-processing', description: 'Computes the pressure difference between two patches', syntax: 'pressureDifference <patch1> <patch2>', commonOptions: '' },
  { name: 'flowRatePatch', category: 'Post-processing', description: 'Computes volumetric/mass flow rate over a patch', syntax: 'flowRatePatch <patch>', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // EXPORT RESULTS
  // ═══════════════════════════════════════════════════════
  { name: 'foamToVTK', category: 'Post-processing', description: 'Exports results in VTK format for ParaView', syntax: 'foamToVTK', commonOptions: '-latestTime, -time <t>' },
  { name: 'foamToEnsight', category: 'Post-processing', description: 'Exports results in EnSight format', syntax: 'foamToEnsight', commonOptions: '-latestTime' },
  { name: 'foamToCSV', category: 'Post-processing', description: 'Exports probe/sets data to CSV', syntax: 'foamToCSV', commonOptions: '' },
  { name: 'foamToSurface', category: 'Post-processing', description: 'Exports patches as surfaces', syntax: 'foamToSurface', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // SAMPLING & PROBES
  // ═══════════════════════════════════════════════════════
  { name: 'sample', category: 'Sampling & Probes', description: 'Performs sampling according to system/sampleDict', syntax: 'sample', commonOptions: '-latestTime' },
  { name: 'setsToVTK', category: 'Sampling & Probes', description: 'Exports topological sets to VTK', syntax: 'setsToVTK', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // PARALLEL PROCESSING
  // ═══════════════════════════════════════════════════════
  { name: 'decomposePar', category: 'Parallel Processing', description: 'Decomposes the case for parallel computation', syntax: 'decomposePar', commonOptions: '-force' },
  { name: 'reconstructPar', category: 'Parallel Processing', description: 'Reconstructs the parallel case into a single domain', syntax: 'reconstructPar', commonOptions: '-latestTime' },
  { name: 'reconstructParMesh', category: 'Parallel Processing', description: 'Reconstructs the parallel mesh', syntax: 'reconstructParMesh', commonOptions: '' },
  { name: 'redistributePar', category: 'Parallel Processing', description: 'Redistributes parallel data across processors', syntax: 'redistributePar', commonOptions: '-decomposeParDict <file>' },

  // ═══════════════════════════════════════════════════════
  // FIELD UTILITIES
  // ═══════════════════════════════════════════════════════
  { name: 'mapFields', category: 'Field Utilities', description: 'Maps fields from one case to another (different meshes)', syntax: 'mapFields <sourceCase> -consistent', commonOptions: '-consistent, -sourceTime <t>' },
  { name: 'mapFieldsPar', category: 'Field Utilities', description: 'Maps fields for parallel cases', syntax: 'mapFieldsPar <sourceCase>', commonOptions: '' },
  { name: 'interpolateFields', category: 'Field Utilities', description: 'Interpolates fields between different meshes', syntax: 'interpolateFields', commonOptions: '' },
  { name: 'foamDictionary', category: 'Field Utilities', description: 'Reads/writes values in OpenFOAM dictionary files', syntax: 'foamDictionary <file> -entry <key>', commonOptions: '-entry, -set, -add, -remove' },

  // ═══════════════════════════════════════════════════════
  // SURFACE UTILITIES
  // ═══════════════════════════════════════════════════════
  { name: 'surfaceTransformPoints', category: 'Surface Utilities', description: 'Applies a transformation to an STL surface', syntax: 'surfaceTransformPoints <input> <output> "rotate=(...) ..."', commonOptions: '' },
  { name: 'surfaceSplitByPatch', category: 'Surface Utilities', description: 'Splits a surface by patch', syntax: 'surfaceSplitByPatch <input> <output>', commonOptions: '' },
  { name: 'surfacePatch', category: 'Surface Utilities', description: 'Adds patch info to a surface', syntax: 'surfacePatch <input> <output>', commonOptions: '' },
  { name: 'surfaceSmooth', category: 'Surface Utilities', description: 'Smooths an STL surface', syntax: 'surfaceSmooth <input> <output>', commonOptions: '' },
  { name: 'surfaceCheck', category: 'Surface Utilities', description: 'Checks STL surface quality', syntax: 'surfaceCheck <file.stl>', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // CASE MANAGEMENT
  // ═══════════════════════════════════════════════════════
  { name: 'foamCleanCase', category: 'Case Management', description: 'Cleans the case (removes mesh, timesteps > 0, logs, processor*)', syntax: 'foamCleanCase', commonOptions: '' },
  { name: 'foamCleanPolyMesh', category: 'Case Management', description: 'Removes only the polyMesh/ directory', syntax: 'foamCleanPolyMesh', commonOptions: '' },
  { name: 'foamCloneCase', category: 'Case Management', description: 'Clones a case (only mesh and 0/)', syntax: 'foamCloneCase <source> <target>', commonOptions: '' },
  { name: 'foamMergeCase', category: 'Case Management', minVersion: 13, description: 'Merges structure and files of multiple cases into one (introduced in v13)', syntax: 'foamMergeCase <source1> <source2> ... <target>', commonOptions: '' },
  { name: 'foamListTimes', category: 'Case Management', description: 'Lists saved timesteps', syntax: 'foamListTimes', commonOptions: '-rm, -latestTime' },
  { name: 'foamGetRange', category: 'Case Management', description: 'Shows the range of timesteps', syntax: 'foamGetRange', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // SOLVER MODULES — modular solvers, specified in controlDict.
  // Introduced in v11, evolved in v12/v13/v14.
  // ═══════════════════════════════════════════════════════
  { name: 'incompressibleFluid', category: 'Solver Modules', minVersion: 11, description: 'Incompressible flow (steady-state/transient, RAS/LES/laminar) — replaces simpleFoam, pimpleFoam, icoFoam', syntax: '(in controlDict: application foamRun; solverModule incompressibleFluid)', commonOptions: '' },
  { name: 'incompressibleVoF', category: 'Solver Modules', minVersion: 11, description: 'Incompressible two-phase VOF — replaces interFoam, interPhaseChangeFoam', syntax: 'solverModule incompressibleVoF', commonOptions: '' },
  { name: 'compressibleFluid', category: 'Solver Modules', minVersion: 11, description: 'Compressible flow (steady-state/transient) — replaces rhoSimpleFoam, rhoPimpleFoam', syntax: 'solverModule compressibleFluid', commonOptions: '' },
  { name: 'compressibleVoF', category: 'Solver Modules', minVersion: 11, description: 'Compressible two-phase VOF', syntax: 'solverModule compressibleVoF', commonOptions: '' },
  { name: 'incompressibleMultiphaseEuler', category: 'Solver Modules', minVersion: 12, description: 'Incompressible Euler-Euler multiphase — replaces multiphaseEulerFoam', syntax: 'solverModule incompressibleMultiphaseEuler', commonOptions: '' },
  { name: 'compressibleMultiphaseEuler', category: 'Solver Modules', minVersion: 12, description: 'Compressible Euler-Euler multiphase', syntax: 'solverModule compressibleMultiphaseEuler', commonOptions: '' },
  { name: 'LagrangianDPM', category: 'Solver Modules', minVersion: 12, description: 'Discrete Phase Model for particles — replaces DPMFoam', syntax: 'solverModule LagrangianDPM', commonOptions: '' },
  { name: 'LagrangianMPPIC', category: 'Solver Modules', minVersion: 12, description: 'Multi-Phase PIC for dense particles — replaces MPPICFoam', syntax: 'solverModule LagrangianMPPIC', commonOptions: '' },
  { name: 'buoyancy', category: 'Solver Modules', minVersion: 11, description: 'Natural convection (Boussinesq/compressible) — replaces buoyantSimpleFoam, buoyantPimpleFoam', syntax: 'solverModule buoyancy', commonOptions: '' },
  { name: 'heatTransfer', category: 'Solver Modules', minVersion: 11, description: 'Conjugate heat transfer solid-fluid — replaces chtMultiRegionFoam', syntax: 'solverModule heatTransfer', commonOptions: '' },
  { name: 'isothermalFluid', category: 'Solver Modules', minVersion: 14, description: 'Improved isothermal fluid for supersonic inlet flow (v14)', syntax: 'solverModule isothermalFluid', commonOptions: '' },
  { name: 'isothermalFilm', category: 'Solver Modules', minVersion: 13, description: 'Isothermal film (thin liquid film) — volumetric flow constraint with fixed velocity BC (v13, improved in v14)', syntax: 'solverModule isothermalFilm', commonOptions: '' },
  { name: 'XiFluid', category: 'Solver Modules', minVersion: 14, description: 'Premixed flame combustion rewritten in v14 as a two-phase solver with MULES — replaces XiFoam', syntax: 'solverModule XiFluid', commonOptions: '' },
  { name: 'DNS', category: 'Solver Modules', minVersion: 12, description: 'Direct Numerical Simulation — replaces dnsFoam', syntax: 'solverModule DNS', commonOptions: '' },
  { name: 'combustion', category: 'Solver Modules', minVersion: 12, description: 'Generic combustion — replaces reactingFoam, fireFoam', syntax: 'solverModule combustion', commonOptions: '' },
  { name: 'solid', category: 'Solver Modules', minVersion: 12, description: 'Solid heat transfer', syntax: 'solverModule solid', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // COMPILATION & DEBUG
  // ═══════════════════════════════════════════════════════
  { name: 'wmake', category: 'Compilation & Debug', description: 'Compiles OpenFOAM C++ source code', syntax: 'wmake', commonOptions: '' },
  { name: 'wclean', category: 'Compilation & Debug', description: 'Cleans compiled files', syntax: 'wclean', commonOptions: '' },
  { name: 'testFoam', category: 'Compilation & Debug', description: 'Test suite for OpenFOAM', syntax: 'testFoam', commonOptions: '' },
  { name: 'foamExec', category: 'Compilation & Debug', description: 'Runs a command in the OpenFOAM environment', syntax: 'foamExec <cmd>', commonOptions: '' },

  // ═══════════════════════════════════════════════════════
  // UNITS & DIMENSIONS — new in v14
  // ═══════════════════════════════════════════════════════
  { name: 'foamUnits', category: 'Units & Dimensions', minVersion: 14, description: 'v14 utility: lists/verifies standard units for input parameters and named dimensions (introduced in v14)', syntax: 'foamUnits', commonOptions: '-list, -verify' },
];

// ── Version-aware filtering ──
//
// Returns the subset of OPENFOAM_COMMANDS compatible with the given major
// OpenFOAM version. If `version` is null/undefined/NaN (e.g. WSL offline or
// version not yet detected), returns ALL commands so the UI is still usable.
export function getCommandsForVersion(version: number | null | undefined): OpenFOAMCommand[] {
  if (version === null || version === undefined || !Number.isFinite(version)) {
    return OPENFOAM_COMMANDS;
  }
  return OPENFOAM_COMMANDS.filter(c => c.minVersion === undefined || version >= c.minVersion);
}

// ── Parse a version string like "14", "v14", "OpenFOAM-14", "13.0" into a major number ──
export function parseMajorVersion(raw: string | null | undefined): number | null {
  if (!raw) return null;
  const m = raw.match(/(\d+)/);
  if (!m) return null;
  const n = parseInt(m[1], 10);
  return Number.isFinite(n) ? n : null;
}
