'use client';

import { useMemo, useState, type FormEvent } from 'react';
import { ComposedChart, Line, XAxis, YAxis, CartesianGrid, ResponsiveContainer, Tooltip } from 'recharts';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
  computeAdvancedAnalysis, validateAdvancedAnalysis, serializeSpectrumCsv, serializeIntervalStatisticsCsv, type AdvancedAnalysisConfig, type QuantityRecipe,
} from '@/lib/postprocess-math';
import { sampleComparisonTrace, serializeComparisonCsv } from '@/lib/postprocess-comparison';
import type { AnalysisDisplayCurve } from '@/lib/postprocess-analysis';

const fieldClass = 'h-8 rounded border bg-background px-2 text-xs';
const format = (value: number | null) => value === null ? '—' : Number(value.toPrecision(7)).toString();
function Field({ name, label, value, optional = false }: { name: string; label: string; value: number | string | null; optional?: boolean }) {
  return <div><Label htmlFor={`analysis-${name}`} className="text-xs">{label}</Label><Input id={`analysis-${name}`} name={name} className="mt-1 h-8 text-xs" defaultValue={value ?? ''} type="number" step="any" required={!optional} /></div>;
}
function SelectField({ name, label, value, options }: { name: string; label: string; value: string; options: { value: string; label: string }[] }) {
  return <div><Label htmlFor={`analysis-${name}`} className="text-xs">{label}</Label><select id={`analysis-${name}`} name={name} defaultValue={value} className={`${fieldClass} mt-1 w-full`} required>{value && !options.some(option => option.value === value) && <option value={value}>Unavailable saved curve ({value})</option>}{options.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select></div>;
}
function NumericalChart({ points, xLabel, yLabel }: { points: { x: number; y: number | null }[]; xLabel: string; yLabel: string }) {
  const sampled = sampleComparisonTrace({ points, sourceOmissions: 0 });
  if (sampled.blocked) return <p className="text-xs text-warning">Chart withheld: the preview budget cannot preserve every gap boundary. Export the numerical CSV.</p>;
  const chartPoints = sampled.points.map((point, index, values) => ({ ...point, isolated: point.y !== null && values[index - 1]?.y == null && values[index + 1]?.y == null }));
  return <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartPoints} margin={{ top: 10, right: 15, bottom: 25, left: 15 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" dataKey="x" domain={['dataMin', 'dataMax']} label={{ value: xLabel, position: 'insideBottom', offset: -15 }} /><YAxis width={70} /><Tooltip /><Line dataKey="y" name={yLabel} stroke="#8b5cf6" isAnimationActive={false} connectNulls={false} type="linear" dot={props => props.payload?.isolated ? <circle key={props.index} cx={props.cx} cy={props.cy} r={2} fill="#8b5cf6" /> : <g key={props.index} />} /></ComposedChart></ResponsiveContainer><p className="text-[10px] text-muted-foreground">Preview {sampled.points.length}/{points.length} points; CSV contains the complete retained output.</p></div>;
}
function download(name: string, csv: string) {
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default function PostProcessAnalysisPanel({ entries, config, onChange, disabled }: {
  entries: AnalysisDisplayCurve[]; config: AdvancedAnalysisConfig; onChange: (config: AdvancedAnalysisConfig) => void; disabled: boolean;
}) {
  const [section, setSection] = useState<'interval' | 'quantities' | 'spectrum' | 'correlation'>('interval');
  const [error, setError] = useState('');
  const [spectrumView, setSpectrumView] = useState<'psd' | 'amplitude'>('psd');
  const sources = useMemo(() => entries.map(entry => ({ key: entry.key ?? entry.trace.id, trace: entry.trace })), [entries]);
  const results = useMemo(() => computeAdvancedAnalysis(sources, config), [sources, config]);
  const curves = sources.map(entry => ({ value: entry.key, label: entry.trace.label }));
  const apply = (next: AdvancedAnalysisConfig) => { try { onChange(validateAdvancedAnalysis(next)); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  const submit = (event: FormEvent<HTMLFormElement>, build: (data: FormData) => AdvancedAnalysisConfig) => {
    event.preventDefault();
    try { apply(build(new FormData(event.currentTarget))); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); }
  };
  const value = (data: FormData, key: string) => Number(data.get(key));
  const optional = (data: FormData, key: string) => data.get(key) === '' ? null : value(data, key);
  const samplingFields = (saved: { sampling: string; step: number; maxGap: number; timeUnit: string } | null) => <>
    <SelectField name="sampling" label="Sampling policy" value={saved?.sampling ?? 'reject'} options={[{ value: 'reject', label: 'Require uniform source samples' }, { value: 'resample', label: 'Explicit linear uniform resampling' }]} />
    <Field name="step" label="Resample Δt (axis units)" value={saved?.step ?? 0.01} /><Field name="maxGap" label="Maximum interpolation gap (axis units)" value={saved?.maxGap ?? 0.1} />
    <SelectField name="timeUnit" label="Declared time-axis unit" value={saved?.timeUnit ?? 's'} options={[{ value: 's', label: 'Seconds' }, { value: 'ms', label: 'Milliseconds' }]} />
  </>;
  return <div className="min-h-0 flex-1 space-y-3 overflow-auto">
    <div className="flex flex-wrap gap-2">{(['interval', 'quantities', 'spectrum', 'correlation'] as const).map(value => <Button key={value} variant={section === value ? 'default' : 'outline'} size="sm" onClick={() => setSection(value)}>{({ interval: 'Interval statistics', quantities: 'Derived quantities / CFD balances', spectrum: 'Spectrum / PSD / Strouhal', correlation: 'Cross-correlation delay' })[value]}</Button>)}</div>
    <p className="text-xs text-muted-foreground">Analysis uses all loaded curves, including hidden curves. Declare compatible physical quantities, units and coordinate frames yourself. The selected interval applies to every operation; derived outputs use the first operand grid. Save analysis persists these settings.</p>
    {error && <p className="text-xs text-warning" role="alert">{error}</p>}
    {results.warnings.length > 0 && <div role="status" className="space-y-1 text-xs text-warning">{results.warnings.map(message => <p key={message}>{message}</p>)}</div>}
    {section === 'interval' && <>
      <form key={`interval-${config.interval.from}-${config.interval.to}`} className="grid max-w-xl grid-cols-3 items-end gap-2" onSubmit={event => submit(event, data => ({ ...config, interval: { from: optional(data, 'from'), to: optional(data, 'to') } }))}><Field name="from" label="Interval start (blank: first)" value={config.interval.from} optional /><Field name="to" label="Interval end (blank: last)" value={config.interval.to} optional /><Button type="submit" size="sm" disabled={disabled}>Apply interval</Button></form>
      <p className="text-xs text-muted-foreground">Population standard deviation equals fluctuation RMS. Time weighting integrates piecewise-linear adjacent finite samples with actual Δt and clips interval boundaries; explicit gaps contribute no duration. Temporal integral is the area over these finite segments, in value × time-axis units; it is not a surface/volume integral or an inferred mass balance. No weighting is applied to spatial profiles. Slope is least-squares against the independent coordinate.</p>
      <div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Curve / coverage</th><th>Mean / RMS</th><th>Fluctuation RMS / SD</th><th>Min / max / peak-to-peak</th><th>Slope</th><th>Time-weighted mean / RMS / fluctuation RMS</th><th>Temporal integral (value × time-axis unit)</th></tr></thead><tbody>{results.statistics.map(entry => <tr key={entry.key} className="border-b align-top"><td className="max-w-sm p-2">{entry.label}{entry.result && <p className="text-[10px] text-muted-foreground">{entry.result.samples} finite, {entry.result.gaps} gaps; covered/requested duration {format(entry.result.coveredDuration)}/{format(entry.result.requestedDuration)}</p>}</td>{entry.result ? <><td>{format(entry.result.mean)} / {format(entry.result.rms)}</td><td>{format(entry.result.fluctuationRms)}</td><td>{format(entry.result.min)} / {format(entry.result.max)} / {format(entry.result.peakToPeak)}</td><td>{format(entry.result.slope)}</td><td>{format(entry.result.weightedMean)} / {format(entry.result.weightedRms)} / {format(entry.result.weightedFluctuationRms)}</td><td>{format(entry.result.integral)}</td></> : <td colSpan={6} className="text-warning">{entry.error}</td>}</tr>)}</tbody></table></div>
      <Button size="sm" variant="outline" disabled={!results.statistics.length} onClick={() => download('interval-statistics.csv', serializeIntervalStatisticsCsv(results.statistics))}>Export interval statistics CSV</Button>
    </>}
    {section === 'quantities' && <>
      <p className="text-xs text-muted-foreground">Difference / pressure drop = A − B. Magnitude uses 2–3 compatible vector components. Coefficients use (A − reference)/scale, Cp = (p − pref)/(½ρU²) for Pa or /(½U²) for kinematic m²/s², force coefficient = (F − Fref)/(½ρU²A). Flux balance sums explicitly signed kg/s or m³/s operands from one case; assign signs yourself, including any existing outward-normal convention.</p>
      <form className="space-y-2 rounded border p-3" onSubmit={event => submit(event, data => {
        const operands = data.getAll('operand').map(String);
        const recipe: QuantityRecipe = { id: crypto.randomUUID(), name: String(data.get('name')), kind: String(data.get('kind')) as QuantityRecipe['kind'], operands,
          alignment: { mode: String(data.get('alignment')) as 'exact' | 'linear', maxGap: value(data, 'quantityGap') }, units: String(data.get('units')), signs: operands.map(key => Number(data.get(`sign-${key}`))),
          coefficient: String(data.get('coefficient')) as QuantityRecipe['coefficient'], reference: value(data, 'reference'), scale: value(data, 'scale'), density: value(data, 'density'), velocity: value(data, 'velocity'), area: value(data, 'area') };
        return { ...config, quantities: [...config.quantities, recipe] };
      })}>
        <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><div><Label htmlFor="quantity-name" className="text-xs">Quantity name</Label><Input id="quantity-name" name="name" required maxLength={128} defaultValue="Derived quantity" className="mt-1 h-8 text-xs" /></div><SelectField name="kind" label="Operation" value="difference" options={[{ value: 'difference', label: 'Difference / pressure drop (A − B)' }, { value: 'magnitude', label: 'Vector magnitude (2–3 components)' }, { value: 'coefficient', label: 'Normalized coefficient' }, { value: 'balance', label: 'Signed mass / volume flux balance' }]} /><div><Label htmlFor="quantity-units" className="text-xs">Declared operand units</Label><Input id="quantity-units" name="units" required maxLength={64} placeholder="Pa, m2/s2, N, kg/s, m3/s…" className="mt-1 h-8 text-xs" /></div><SelectField name="alignment" label="Operand grids" value="exact" options={[{ value: 'exact', label: 'Exact coordinates only' }, { value: 'linear', label: 'Explicit linear onto first operand' }]} /></div>
        <p className="text-xs">Choose operands in displayed curve order (A first, B second). Signed balance orientation applies only to the balance operation.</p>
        {sources.map(entry => <label key={entry.key} className="flex items-center gap-2 text-xs"><input type="checkbox" name="operand" value={entry.key} /><span className="min-w-0 flex-1 truncate" title={entry.trace.label}>{entry.trace.label}</span><select name={`sign-${entry.key}`} className={fieldClass} aria-label={`Flux orientation ${entry.trace.label}`} defaultValue="1"><option value="1">+1</option><option value="-1">−1</option></select></label>)}
        <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Field name="quantityGap" label="Maximum interpolation gap" value={0.1} /><SelectField name="coefficient" label="Coefficient normalization" value="reference" options={[{ value: 'reference', label: 'User reference scale (same input units)' }, { value: 'pressure', label: 'Pressure coefficient Cp' }, { value: 'force', label: 'Force coefficient' }]} /><Field name="reference" label="Reference / offset (input units)" value={0} /><Field name="scale" label="Reference scale (same input units)" value={1} /><Field name="density" label="ρ reference (kg/m³)" value={1} /><Field name="velocity" label="U reference (m/s)" value={1} /><Field name="area" label="A reference (m²)" value={1} /></div>
        <Button size="sm" type="submit" disabled={disabled || sources.length === 0 || config.quantities.length >= 6}>Add derived recipe</Button>
      </form>
      {config.quantities.map(recipe => { const trace = results.quantities.find(trace => trace.id === recipe.id); const balance = results.balances.find(item => item.id === recipe.id); return <div key={recipe.id} className="space-y-2 rounded border p-3"><div className="flex items-center gap-2"><strong className="flex-1 text-sm">{recipe.name} · {recipe.kind === 'coefficient' ? 'dimensionless' : recipe.units}</strong><Button size="sm" variant="ghost" disabled={disabled} onClick={() => apply({ ...config, quantities: config.quantities.filter(q => q.id !== recipe.id) })}>Remove recipe</Button>{trace && <Button size="sm" variant="outline" onClick={() => download('derived-quantity.csv', serializeComparisonCsv([trace]))}>CSV</Button>}</div>{balance && <p className="text-xs">Balance: last net {format(balance.lastNet)} {recipe.units}; maximum |net| {format(balance.maxAbsoluteNet)}; maximum relative imbalance {format(balance.maxRelativePercent)}% = 100·|signed sum|/sum(|operand flux|). Undefined at zero total flux; storage/source terms and density are not inferred.</p>}{trace && <><p className="text-xs text-muted-foreground">{trace.source} · {trace.coverage}</p><NumericalChart points={trace.points} xLabel={trace.axis} yLabel={trace.field} /><div className="max-h-40 overflow-auto"><table className="w-full text-xs"><thead><tr><th>Coordinate</th><th>{trace.field}</th></tr></thead><tbody>{trace.points.slice(0, 100).map((point, index) => <tr key={index}><td>{format(point.x)}</td><td>{format(point.y)}</td></tr>)}</tbody></table></div><p className="text-[10px]">Table: first {Math.min(100, trace.points.length)}/{trace.points.length}; CSV preserves all loaded rows and gaps.</p></>}</div>; })}
    </>}
    {section === 'spectrum' && <>
      <p className="text-xs text-muted-foreground">A contiguous time series and declared time unit are required. Irregular sampling is rejected unless you explicitly resample. Choose the exact FFT sample count: the first N samples in the interval are used, with no zero padding. Hann uses a periodic window; PSD is a one-sided periodogram. The peak frequency is a bin estimate, not a convergence or significance test.</p>
      <form key={`spectrum-${JSON.stringify(config.spectrum)}`} className="grid grid-cols-2 items-end gap-2 rounded border p-3 lg:grid-cols-4" onSubmit={event => submit(event, data => ({ ...config, spectrum: { curve: String(data.get('curve')), window: String(data.get('window')) as 'hann' | 'rectangular', detrend: String(data.get('detrend')) as 'mean' | 'none', sampling: String(data.get('sampling')) as 'reject' | 'resample', step: value(data, 'step'), maxGap: value(data, 'maxGap'), samples: value(data, 'samples'), timeUnit: String(data.get('timeUnit')) as 's' | 'ms', valueUnits: String(data.get('valueUnits')), length: optional(data, 'length'), velocity: optional(data, 'strouhalVelocity') } }))}>
        <SelectField name="curve" label="Time-series curve" value={config.spectrum?.curve ?? curves[0]?.value ?? ''} options={curves} /><SelectField name="window" label="Window" value={config.spectrum?.window ?? 'hann'} options={[{ value: 'hann', label: 'Periodic Hann' }, { value: 'rectangular', label: 'Rectangular' }]} /><SelectField name="detrend" label="Detrending" value={config.spectrum?.detrend ?? 'mean'} options={[{ value: 'mean', label: 'Remove sample mean' }, { value: 'none', label: 'None (retain DC)' }]} /><Field name="samples" label="FFT N (power of 2, 8–16,384)" value={config.spectrum?.samples ?? 64} />{samplingFields(config.spectrum)}<div><Label htmlFor="signal-units" className="text-xs">Declared signal units</Label><Input id="signal-units" name="valueUnits" required maxLength={64} defaultValue={config.spectrum?.valueUnits ?? ''} placeholder="Pa, m/s, dimensionless…" className="mt-1 h-8 text-xs" /></div><Field name="length" label="Strouhal reference L (m, optional)" value={config.spectrum?.length ?? null} optional /><Field name="strouhalVelocity" label="Strouhal reference U (m/s, optional)" value={config.spectrum?.velocity ?? null} optional /><Button size="sm" type="submit" disabled={disabled || !curves.length}>Compute spectrum</Button>
      </form>
      {config.spectrum && <Button size="sm" variant="ghost" onClick={() => apply({ ...config, spectrum: null })} disabled={disabled}>Clear spectrum settings</Button>}
      {results.spectrum && <><p className="text-sm font-medium">Dominant frequency {format(results.spectrum.dominantFrequency)} Hz · Strouhal {format(results.spectrum.strouhal)} · Δf {format(results.spectrum.frequencyResolution)} Hz · Nyquist {format(results.spectrum.nyquist)} Hz</p><p className="text-xs text-muted-foreground">{results.spectrum.notes} Used interval {results.spectrum.from}–{results.spectrum.to}.</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setSpectrumView(value => value === 'psd' ? 'amplitude' : 'psd')}>{spectrumView === 'psd' ? 'Show amplitude spectrum' : 'Show PSD'}</Button><Button size="sm" variant="outline" onClick={() => download('spectrum.csv', serializeSpectrumCsv(results.spectrum!, config.spectrum?.valueUnits ?? "unknown"))}>Spectrum CSV</Button></div><NumericalChart points={results.spectrum.points.map(point => ({ x: point.frequency, y: point[spectrumView] }))} xLabel="Frequency (Hz)" yLabel={spectrumView === 'psd' ? 'PSD' : 'Peak amplitude'} /></>}
    </>}
    {section === 'correlation' && <>
      <p className="text-xs text-muted-foreground">A positive delay means B follows A: sum A(t)·B(t+delay). Both signals are mean-centered over their common interval; coefficients use overlap-energy normalization. At least half of the samples overlap at every lag. Periodic signals can have ambiguous peaks. No interpolation or extrapolation is applied without the explicit sampling choice.</p>
      <form key={`correlation-${JSON.stringify(config.correlation)}`} className="grid grid-cols-2 items-end gap-2 rounded border p-3 lg:grid-cols-4" onSubmit={event => submit(event, data => ({ ...config, correlation: { first: String(data.get('first')), second: String(data.get('second')), sampling: String(data.get('sampling')) as 'reject' | 'resample', step: value(data, 'step'), maxGap: value(data, 'maxGap'), maxLag: value(data, 'maxLag'), timeUnit: String(data.get('timeUnit')) as 's' | 'ms' } }))}>
        <SelectField name="first" label="First curve A" value={config.correlation?.first ?? curves[0]?.value ?? ''} options={curves} /><SelectField name="second" label="Second curve B" value={config.correlation?.second ?? curves[1]?.value ?? ''} options={curves} />{samplingFields(config.correlation)}<Field name="maxLag" label="Maximum lag samples (0–512)" value={config.correlation?.maxLag ?? 32} /><Button size="sm" type="submit" disabled={disabled || curves.length < 2}>Compute delay</Button>
      </form>
      {config.correlation && <Button size="sm" variant="ghost" disabled={disabled} onClick={() => apply({ ...config, correlation: null })}>Clear delay settings</Button>}
      {results.correlation && <><p className="text-sm font-medium">B follows A by {format(results.correlation.delay)} s · correlation {format(results.correlation.correlation)} · {results.correlation.samples} samples</p><p className="text-xs text-muted-foreground">{results.correlation.notes}</p><Button size="sm" variant="outline" onClick={() => download('cross-correlation.csv', 'Delay (s),Normalized correlation,Overlap pairs\n' + results.correlation!.points.map(point => [point.delay, point.correlation, point.pairs].join(',')).join('\n'))}>Delay CSV</Button><NumericalChart points={results.correlation.points.map(point => ({ x: point.delay, y: point.correlation }))} xLabel="Delay (s)" yLabel="Normalized correlation" /></>}
    </>}
  </div>;
}
